GestionTaches/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'lesTaches/', include('lesTaches.urls')),
    path(r'contacts/', include('myform.urls'))
]

lesTaches/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(r'home/<param>', views.home, name='home'),
    path(r'listing', views.task_listing, name='listing')
]

myform/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.contact, name='contact'),
    path('detail/<int:cid>', views.detail, name='detail'),
    path('edit/<int:pers_id>', views.edit, name='edite'),
    path('listing/', views.contact_listing, name='listing'),
    path('delete/<int:pers_id>', views.delete, name='delete'),



]

lesTaches/models.py
from django.db import models
from datetime import date, timedelta
from django.utils.html import format_html

from django.template.defaultfilters import date as django_date

# Create your models here.

class Task(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    created_date = models.DateField(auto_now_add=True)
    scheduled_date = models.DateField(null=True)
    due_date = models.DateField(null=True)
    closed = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def colored_due_date(self):
        due_date = django_date(self.due_date,"d F Y")
        if self.due_date-timedelta(days=7) > date.today():
            color = "green"
        elif self.due_date < date.today():
            color = "red"
        else:
            color = "orange"
        return format_html("<span style=color:%s>%s</span>"
         % (color, due_date))

    colored_due_date.allow_tags = True
    

myform/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=50)
    firstname = models.CharField(max_length=50)
    email = models.EmailField(max_length=200)
    message = models.TextField(max_length=1000)
   

lesTaches/views.py
from django.shortcuts import render

from django.http import HttpResponse

# Create your views here.

def home(request, param):
    return HttpResponse("Hello Django ! "+param)

from lesTaches.models import Task

def task_listing(request):
    objects = Task.objects.all().order_by('due_date')
    
    return render(request, template_name='list2.html', context={'objects': objects} )

myform/views.py
from django.shortcuts import render, redirect
from django.forms import ModelForm, Textarea
from myform.models import Contact
from django import forms
from django.urls import reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect

# Create your views here.

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'firstname', 'email', 'message')
        widgets = {
            'message': forms.Textarea(attrs={'cols':20, 'rows': 10,
                'placeholder': 'Entrer votre message ici'}),
            'name': forms.TextInput(attrs={'placeholder': 'Doe'})
        }
        labels = {
        "name": "Nom",
        "firstname": "Prénom",
    }

from django import forms

class ContactForm2(forms.Form):
    name = forms.CharField(max_length=50, initial="Votre nom", label="nom")
    firstname = forms.CharField(max_length=50,  initial="Votre prénom",
    label="prenom")
    email = forms.EmailField(max_length=200, label='mail')
    message = forms.CharField(max_length=1000,
    widget=forms.Textarea(attrs={'cols':20, 'rows': 10}))

def contact(request):
    # on instancie un formulaire
    form = ContactForm()
    # on teste si on est bien en validation de formulaire (POST)
    if request.method == "POST":
        # Si oui on récupère les données postées
        form = ContactForm(request.POST)
        # on vérifie la validité du formulaire
        if form.is_valid():
            new_contact = form.save()
            return redirect(reverse('detail', args=[new_contact.pk] ))
    # Si méthode GET, on présente le formulaire
    context = {'form': form}
    return render(request,'contact.html', context)

def edit(request, pers_id):
    # on récupère la personne
    pers = Contact.objects.get(pk=pers_id)
    # on teste si on est bien en validation de formulaire (POST)
    if request.method == "POST":
        # Si oui on récupère les données postées
        form = ContactForm(request.POST, instance=pers)
        # on vérifie la validité du formulaire
        if form.is_valid():
            form.save()
            return redirect(reverse('detail', args=[pers_id] ))
    # Si méthode GET, on présente le formulaire
    form = ContactForm(instance=pers)
    context = {'form': form}
    return render(request,'contact.html', context)

def delete(request, pers_id):
    pers = Contact.objects.get(pk=pers_id)
    pers.delete()
    return HttpResponseRedirect("/contacts/listing/")
    #return render(request,'list_contacts.html')

def detail(request, cid):
    contact = Contact.objects.get(pk=cid)
    return render(request, template_name='detail_contact.html', context={'contact': contact} )

def contact_listing(request):
    objects = Contact.objects.all().order_by('id')

    return render(request, template_name='list_contacts.html', context={'objects': objects} )

lesTaches/templates/base.html
<!doctype html>
{%load static %}
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}{% endblock %}
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% block styles %}
        <link rel="stylesheet"
              href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        {% endblock %}
    </head>
    <body>
            <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
            <h1> Gestion des Tâches</h1>
            </nav>

        <main role="main" class="container top-pushed">
            <div class="jumbotron">
                {% block content %}
                {% endblock %}
            </div>
        </main>

        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}">
        </script>
    </body>
</html>

lesTaches/templates/baseLayout.html
<!doctype html>
{%load static %}
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>Les Tâches</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet"
              href="{% static 'bootstrap/css/bootstrap.min.css' %}"> 
    </head>
    <body>  
            <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
                <a class="navbar-brand" href="#">Navbar</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
              
                    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                      <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                          <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                          </div>
                        </li>
                      </ul>
                      <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                      </form>
                    </div>
                  </nav>
              
        <main role="main" class="container">
              
            {% block content %}
            {% endblock %}
              
        </main>
        <!-- /.container -->
              
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}">
        </script>
    </body>
</html>

lesTaches/templates/list.html
{% extends "base.html" %}
    {% load static %}

    {% block content %}
    <h1>Liste des tâches</h1>
    <ul>
    {% for elem in objects %}
        <li>{{elem}}</li>
    {% endfor %}
    </ul>

    {% endblock %}

lesTaches/templates/list2.html
{% extends "base.html" %}
    {% load static %}
    {% block title %}
        Les Tâches
    {% endblock %}

    {% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
          crossorigin="anonymous">
    {% endblock %}
    {% block content %}
    <h1>Liste des tâches</h1>



    {% for tache in objects %}
    <div class="row">
        <div class="col">{{tache.name}}</div>
        <div class="col">{{tache.created_date}}</div>
        <div class="col">{{tache.colored_due_date}}</div>
        <div class="col">
                {% if tache.closed %}
                    <i class="fas fa-lock"></i>
                {% else %}
                    <i class="fas fa-lock-open"></i>
                {% endif %}
        </div>

    </div>
    {% endfor %}



    {% endblock %}

myform/templates/base_myform.html
<!doctype html>
{%load static %}
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}{% endblock %}
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% block styles %}
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        {% endblock %}
    </head>
    <body>
            <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
            <h1> Gestion des Contacts</h1>
            </nav>

        <main role="main" class="container top-pushed">
            <div class="jumbotron">
                {% block content %}
                {% endblock %}
            </div>
        </main>

        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}">
        </script>
    </body>
</html>

myform/templates/contact.html
{% extends "base_myform.html" %}
    {% load static %}
    {% block title %}
    {% if form.name.value %}
        Modifier le contact {{form.firstname.value}} {{form.name.value}}
    {% else %}
        Ajouter un contact
    {% endif %}
    {% endblock %}

    {% block content %}

    {% if form.name.value %}
        <h1>Modifier un contact</h1>
    {% else %}
        <h1>Nouveau contact</h1>
    {% endif %}

    <a href="/contacts/listing" style="margin-bottom: 10px;" type="button" class="btn btn-primary">Voir la liste des contacts</a>

    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label">Nom</label>
            <div class="col-10">
                <input class="form-control" type="text" value="{{ form.name.value|default_if_none:"" }}" name="name" id="id_name">
            </div>
        </div>
        <div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label">Prenom</label>
            <div class="col-10">
                <input class="form-control" type="text" value="{{ form.firstname.value|default_if_none:"" }}" name="firstname" id="id_firstname">
            </div>
        </div>
        <div class="form-group row">
            <label for="example-text-input" class="col-2 col-form-label">Email</label>
            <div class="col-10">
                <input class="form-control" type="text" value="{{ form.email.value|default_if_none:"" }}" name="email" id="id_email">
            </div>
        </div>
        <div class="form-group">
            <label for="exampleTextarea">Message</label>
            <textarea class="form-control" name="message" id="id_message" rows="3">{{ form.message.value|default_if_none:"" }}</textarea>
        </div>

        <input type="submit" value="Sauvegarder"/>
    </form>

    {% endblock %}

myform/templates/detail_contact.html
{% extends "base_myform.html" %}
    {% load static %}
    {% block title %}
        Détails du contact {{contact.firstname}} {{contact.name}}
    {% endblock %}

    {% block content %}
    <h1>Détails du contact</h1>
    <a href="/contacts/listing" style="margin-bottom: 10px;" type="button" class="btn btn-primary">Voir la liste des contacts</a>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">First</th>
          <th scope="col">Email</th>
          <th scope="col">Message</th>
        </tr>
      </thead>
      <tbody>
          <tr>
              <td>{{contact.id}}</td>
              <td>{{contact.name}}</td>
              <td>{{contact.firstname}}</td>
              <td>{{contact.email}}</td>
              <td>{{contact.message}}</td>
          </tr>
      </tbody>
    </table>
    {% endblock %}

myform/templates/list_contacts.html
{% extends "base_myform.html" %}
    {% load static %}
    {% block title %}
        Liste de vos contacts
    {% endblock %}

    {% block content %}
    <h1>Liste des contacts</h1>
    <a href="/contacts" style="margin-bottom: 10px;" type="button" class="btn btn-primary">Nouveau contact</a>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Nom</th>
          <th scope="col">Prénom</th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
          {% for contact in objects %}
              <tr>
                  <td>{{contact.name}}</td>
                  <td>{{contact.firstname}}</td>
                  <td><a href="../detail/{{contact.id}}"><i class="fas fa-info-circle"></i></a></td>
                  <td><a href="../edit/{{contact.id}}"><i class="far fa-edit"></i></a></td>
                  <td><a href="../delete/{{contact.id}}"><i class="fas fa-trash-alt"></i></a></td>
              </tr>
          {% endfor %}
      </tbody>
    </table>

    {% endblock %}